const a = 'feijaopretoDJASOIDJOIDJDOIAJDSAOIDJSAOIDJASDOISAJDOAJDOSAIJDASOIDJASOIDJASIODJASOIDJASODJASOIDJASOIDJASOIDJASOIDJADOIAJDOIASDJAODJ'
console.log('a length:', a.length);

const newA = a.slice(2) + '...';
console.log(newA);